### PR TITLE
CMake Refactor in ctp

### PR DESCRIPTION
**Pull request by junghans**
Part of https://github.com/votca/votca/pull/160

### CODE REVIEW

**Comment by crionez** [comment]
You removed GSL and made Eigen3 the only required package. Before I could have either Eigen or GSL linear algebra support, depending on the flag in CMake. Is this restriction really needed?

**Comment by junghans** [comment]
@crionez, this pull request doesn't touch GSL support, I left it in the exact state as before, GSL support was disabled in https://github.com/votca/ctp/commit/709fd1ab38abcfdec2e008ea8a4e2ee4596b46c4#diff-af3b638bc2a3e6c650974192a53c7291R62.

**Comment by junghans** [comment]
@crionez see #129 for the GSL issue.

**Comment by junghans** [comment]
Fix merged that fix, but ctp will still require Eigen3 as it is used everywhere in the votca tools headers.

**Pull request merged**
